name: 测试用例完善
description: 测试用例完善，性能压测等
title: "[测试&性能]: "
labels: ["test"]
body:
  - type: markdown
    attributes:
      value: |
        感谢提出功能建议，我们将仔细考虑！
  - type: textarea
    id: related-problem
    attributes:
      label: 你需要哪些测试用例，性能压测数据？
      description: 你需要哪些测试用例，性能压测数据？
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: 意向参与贡献
      options:
        - label: 我有意向参与具体功能的开发实现并将代码贡献回到上游社区
          required: false