name: 构建或者辅助工具建议
description: 构建过程或辅助工具
title: "[构建&辅助]: "
labels: ["build"]
body:
  - type: markdown
    attributes:
      value: |
        感谢提出功能建议，我们将仔细考虑！
  - type: textarea
    id: related-problem
    attributes:
      label: 你的构建或者辅助工具建议？
      description: 清晰并简洁地描述问题是什么？
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: 意向参与贡献
      options:
        - label: 我有意向参与具体功能的开发实现并将代码贡献回到上游社区
          required: false
